disabled_rules:
    - class_delegate_protocol
    - closing_brace
    - colon
    - comma
    - comment_spacing
    - compiler_protocol_init
    - computed_accessors_order
    - control_statement
    - cyclomatic_complexity
    - empty_enum_arguments
    - empty_parentheses_with_trailing_closure
    - file_length
    - force_cast
    - force_try
    - for_where
    - function_body_length
    - function_parameter_count
    - identifier_name
    - implicit_getter
    - is_disjoint
    - large_tuple
    - leading_whitespace
    - legacy_constructor
    - legacy_random
    - line_length
    - mark
    - multiple_closures_with_trailing_closure
    - nesting
    - no_fallthrough_only
    - no_space_in_method_call
    - opening_brace
    - operator_whitespace
    - orphaned_doc_comment
    - private_over_fileprivate
    - redundant_discardable_let
    - redundant_objc_attribute
    - redundant_optional_initialization
    - redundant_string_enum_value
    - redundant_void_return
    - return_arrow_whitespace
    - shorthand_operator
    - statement_position
    - switch_case_alignment
    - syntactic_sugar
    - todo
    - trailing_comma
    - trailing_newline
    - trailing_semicolon
    - trailing_whitespace
    - type_body_length
    - type_name
    - unneeded_break_in_switch
    - unused_closure_parameter
    - unused_optional_binding
    - vertical_whitespace
    - void_return
    - xctfail_message