language: objective-c
osx_image: xcode6.4
install:
  - make travis-get-deps
script: bundle exec fastlane travis
after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only: 
    - master

