name: CI

on:
  pull_request:
    
jobs:
  test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache bundle install
      uses: actions/cache@v2
      env:
        cache-name: cache-bundle-install
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install ruby gems for fastlane
      run: |
        bundle config path vendor/bundle
        bundle install

    - name: Run tests
      run: bundle exec fastlane verify_pull_request

    - name: Upload test report html
      uses: actions/upload-artifact@v2
      with:
        name: test-report-html
      path: fastlane/test_output/report.html

    - name: Upload test report junit
      uses: actions/upload-artifact@v2
      with:
        name: test-report-junit
      path: fastlane/test_output/report.junit
